/* eslint-disable @next/next/no-sync-scripts */
import type { Metadata } from 'next'

import './globals.css'



import Header from './components/Header/Header'

import Head from 'next/head'

import Footer from './components/Footer/Footer'
import StoreProvider from '@/redux/StoreProvider/StoreProvider'

import { routesItems } from './constant/constant'
import Script from 'next/script'

<Script
        src='https://api-maps.yandex.ru/2.1/?apikey=c9273e50-6b61-4b69-a5a9-4ba1f010ec6a&lang=ru_RU'
        
      />



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',

}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <StoreProvider>
     
      <html lang="ru">
          <Head>
            <meta name="google-site-verification" content="google67984ba37c9a9849.html" />
          </Head>
          <body >
            <Header />
            <main style={{ maxWidth: '1244px', margin: '0 auto' }}>
                 {children}
            </main>
            <Footer routes={routesItems} />
          </body>
        </html>
     
        
    </StoreProvider>
  )
}
