import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'



import Header from './components/Header/Header'
import Footer from './components/Footer/Footer'
import MainMenu from './components/MainMenu/MainMenu'
import Head from 'next/head'
import StoreProvider from './redux/StoreProvider/StoreProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',

}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <StoreProvider>
      <html lang="ru">
        <Head>
          <meta name="google-site-verification" content="google67984ba37c9a9849.html" />

        </Head>
        <body className={inter.className}>
          <Header />
          <MainMenu />
          <main style={{ maxWidth: '1244px', margin: '0 auto' }}>
            {children}
          </main>

          <Footer />
        </body>
      </html>
    </StoreProvider>

  )
}
